# Generated by Django 2.0 on 2020-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='uf',
            field=models.CharField(max_length=2),
        ),
    ]
